// Storage layer for dsh-research-lab: <project>/.rlab/ with path-safety guards.
import * as fs from 'node:fs';
import * as path from 'node:path';

const RLAB_DIR = '.rlab';

export function rlabDir(project: string): string {
  const abs = path.resolve(project);
  return path.join(abs, RLAB_DIR);
}

function ensureDir(p: string) {
  fs.mkdirSync(p, { recursive: true });
}

function readJson<T>(file: string, fallback: T): T {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8')) as T;
  } catch {
    return fallback;
  }
}

function writeJson(file: string, data: unknown) {
  ensureDir(path.dirname(file));
  const tmp = file + '.tmp';
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2), 'utf8');
  fs.renameSync(tmp, file);
}

// ---------- wiki pages ----------
export type WikiKind = 'experiment' | 'literature' | 'decision' | 'todo';
export interface WikiPage {
  kind: WikiKind;
  id: string;
  title: string;
  updated: string;
  content: string;
  tags?: string[];
}

const WIKI_DIR = 'wiki';

// OmegaWiki frontmatter: --- block of key: value lines (shared contract with rlab_validate)
export function parseFrontmatter(text: string): Record<string, string | string[]> {
  const out: Record<string, string | string[]> = {};
  const m = text.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!m) return out;
  for (const line of m[1].split('\n')) {
    const mm = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!mm) continue;
    const key = mm[1];
    const val = mm[2].trim();
    if (val.startsWith('[') && val.endsWith(']')) {
      out[key] = val.slice(1, -1).split(',').map(s => s.trim()).filter(Boolean);
    } else {
      out[key] = val;
    }
  }
  return out;
}

export function wikiPath(project: string, kind: WikiKind, id: string): string {
  const safe = id.replace(/[^A-Za-z0-9_.-]/g, '_');
  return path.join(rlabDir(project), WIKI_DIR, kind, safe + '.md');
}

export function writeWikiPage(project: string, page: WikiPage): string {
  const p = wikiPath(project, page.kind, page.id);
  const fm = [
    '---',
    'id: ' + page.id,
    'kind: ' + page.kind,
    'title: ' + page.title.replace(/\n/g, ' '),
    'updated: ' + page.updated,
    (page.tags?.length ? 'tags: [' + page.tags.join(', ') + ']' : 'tags: []'),
    '---',
    '',
  ].join('\n');
  const body = [
    fm,
    '# ' + page.title,
    '',
    page.content.trim(),
    '',
  ].join('\n');
  ensureDir(path.dirname(p));
  fs.writeFileSync(p, body, 'utf8');
  // append-only operation log (AutoSci hard rule: wiki/log.md never rewritten in place)
  const log = path.join(rlabDir(project), 'wiki', 'log.md');
  const stamp = new Date().toISOString();
  fs.appendFileSync(log, '- ' + stamp + '  ' + page.kind + ':' + page.id + '  ' + page.title.replace(/[\r\n]+/g, ' ') + '\n', 'utf8');
  return p;
}

export function listWiki(project: string): WikiPage[] {
  const root = path.join(rlabDir(project), WIKI_DIR);
  const pages: WikiPage[] = [];
  const kinds: WikiKind[] = ['experiment', 'literature', 'decision', 'todo'];
  for (const kind of kinds) {
    const dir = path.join(root, kind);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir)) {
      if (!f.endsWith('.md')) continue;
      const full = path.join(dir, f);
      const text = fs.readFileSync(full, 'utf8');
      const fm = parseFrontmatter(text);
      const title = String(fm.title || (text.match(/^# (.+)$/m) || [])[1] || f.replace(/\.md$/, ''));
      const updated = String(fm.updated || '');
      const tags: string[] = Array.isArray(fm.tags) ? fm.tags : (fm.tags ? [String(fm.tags)] : []);
      pages.push({ kind, id: f.replace(/\.md$/, ''), title, updated, tags, content: '' });
    }
  }
  return pages.sort((a, b) => a.kind.localeCompare(b.kind) || a.id.localeCompare(b.id));
}

export function rebuildWikiIndex(project: string): string {
  const pages = listWiki(project);
  const lines = ['# Research Wiki Index', '', 'Auto-generated by dsh-research-lab. Do not edit by hand.', ''];
  const kinds: { k: WikiKind; label: string }[] = [
    { k: 'experiment', label: '## Experiments' },
    { k: 'literature', label: '## Literature' },
    { k: 'decision', label: '## Decisions' },
    { k: 'todo', label: '## TODO' },
  ];
  for (const { k, label } of kinds) {
    const sub = pages.filter(p => p.kind === k);
    if (!sub.length) continue;
    lines.push(label);
    for (const p of sub) {
      lines.push('- [' + p.title + '](wiki/' + k + '/' + p.id + '.md)' + (p.updated ? '  _' + p.updated + '_' : ''));
    }
    lines.push('');
  }
  const idx = path.join(rlabDir(project), WIKI_DIR, 'index.md');
  ensureDir(path.dirname(idx));
  fs.writeFileSync(idx, lines.join('\n') + '\n', 'utf8');
  return idx;
}

// ---------- bench ledger (JSONL, one row per run) ----------
export interface BenchRow {
  date: string;
  model: string;
  task: string;
  metric: string;   // e.g. cos_sim.spearman | ndcg_at_10 | accuracy
  score: number;
  split?: string;   // test | dev | validation — CRITICAL: splits are NOT comparable
  hf_subset?: string;
  prompt_type?: string;
  seed?: number;
  note?: string;
}

export function benchFile(project: string): string {
  return path.join(rlabDir(project), 'bench.jsonl');
}

export function appendBench(project: string, row: BenchRow): BenchRow[] {
  const file = benchFile(project);
  ensureDir(path.dirname(file));
  fs.appendFileSync(file, JSON.stringify(row) + '\n', 'utf8');
  return readBench(project);
}

export function readBench(project: string): BenchRow[] {
  const file = benchFile(project);
  if (!fs.existsSync(file)) return [];
  const rows: BenchRow[] = [];
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    if (!line.trim()) continue;
    try { rows.push(JSON.parse(line) as BenchRow); } catch { /* skip bad line */ }
  }
  return rows;
}

export function benchReport(project: string, model?: string, task?: string): string {
  let rows = readBench(project);
  if (!rows.length) return 'No benchmark rows yet for ' + project + '. Add one with rlab_bench.';
  if (model) rows = rows.filter(r => r.model.toLowerCase().includes(model.toLowerCase()));
  if (task) rows = rows.filter(r => r.task.toLowerCase().includes(task.toLowerCase()));
  if (!rows.length) return 'No rows match the filter.';
  const lines = ['# Bench ledger — ' + project, ''];
  // group by task
  const byTask = new Map<string, BenchRow[]>();
  for (const r of rows) {
    const arr = byTask.get(r.task) || [];
    arr.push(r);
    byTask.set(r.task, arr);
  }
  for (const [t, rs] of [...byTask.entries()].sort()) {
    lines.push('## ' + t + '  (' + rs.length + ' runs)');
    const byModel = new Map<string, BenchRow[]>();
    for (const r of rs) {
      const arr = byModel.get(r.model) || [];
      arr.push(r);
      byModel.set(r.model, arr);
    }
    for (const [m, mr] of [...byModel.entries()].sort()) {
      const latest = mr[mr.length - 1];
      const all = mr.map(r => r.score.toFixed(4)).join(' → ');
      lines.push('- **' + m + '**  latest=' + latest.score.toFixed(4) + ' (' + latest.metric + ')  history=[' + all + ']');
      if (latest.split) lines.push('  - split=' + latest.split + (latest.hf_subset ? ' subset=' + latest.hf_subset : '') + '  ' + latest.date + (latest.note ? '  — ' + latest.note : ''));
    }
    //口径 warning: different splits compared?
    const splits = new Set(rs.map(r => r.split || '?'));
    if (splits.size > 1) {
      lines.push('  ⚠️ **口径不一致**: runs use different splits (' + [...splits].join(', ') + ') — do NOT compare across splits.');
    }
    lines.push('');
  }
  lines.push('_Ledger: ' + benchFile(project) + '_');
  return lines.join('\n');
}